name: "\U0001F680 Feature Proposal"
description: Propose a new feature for function-al
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature for function-al! 

        📖 Before submitting, please read the [Contributing Guide](https://github.com/hwanheejung/function-al/blob/main/CONTRIBUTING.md).

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description:
        Provide a clear and concise description of the proposed feature
      placeholder:
        "As a developer using function-al, I want [feature] so that [benefit]."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature would be useful for the library
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature being implemented

  - type: checkboxes
    id: contribution-checklist
    attributes:
      label: Contribution Checklist
      options:
        - label: I have read the Contributing Guide
          required: true
        - label: I believe this feature aligns with the library's goals
          required: true
