name: "\U0001F4DD Refactoring Proposal"
description: Suggest code improvements or refactoring for function-al
labels: ["refactoring"]
body:
  - type: markdown
    attributes:
      value: |
        Help improve the library's code quality!

        📖 Before submitting, please read the [Contributing Guide](https://github.com/hwanheejung/function-al/blob/main/CONTRIBUTING.md).

  - type: textarea
    id: current-implementation
    attributes:
      label: Current Implementation
      description: Describe the current code that needs refactoring
    validations:
      required: true

  - type: textarea
    id: proposed-refactoring
    attributes:
      label: Proposed Refactoring
      description: Explain your suggested improvements
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What improvements will this refactoring bring?
    validations:
      required: true
