name: "\U0001F4DD Refactoring Proposal"
description: Suggest code improvements or refactoring for function-al
labels: ["refactoring"]
body:
  - type: textarea
    id: current-implementation
    attributes:
      label: Current Implementation
      description: Describe the current code that needs refactoring
    validations:
      required: true

  - type: textarea
    id: proposed-refactoring
    attributes:
      label: Proposed Refactoring
      description: Explain your suggested improvements
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What improvements will this refactoring bring?
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm before submitting
      options:
        - label: I have checked that this issue does not already exist.
          required: true
        - label:
            I have read the [Contributing
            Guide](https://github.com/hwanheejung/function-al/blob/main/CONTRIBUTING.md).
          required: true
        - label: I am using the latest version of function-al.
          required: false
