export { spreadArgs } from "./spreadArgs/spreadArgs.js";
export { gatherArgs } from "./gatherArgs/gatherArgs.js";
export { identity } from "./identity/identity.js";
export { partial } from "./partial/partial.js";
export { curry } from "./curry/curry.js";
export { unary } from "./unary/unary.js";
export { pipe } from "./pipe/pipe.js";
export { compose } from "./compose/compose.js";
export { noop } from "./noop/noop.js";
